dj_map/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dj_map_app.urls')),
    path('users/', include('users_app.urls')),
]

dj_map_app/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

# app namespace
app_name = 'dj_map_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('large', views.large, name='large'),
    path('points', views.points, name='points'),
    url(r'^points.data/', views.points_data, name='points_data'),
    url(r'^points.nearby/', views.nearby_points_data, name='nearby_points_data'),
    path('points/<int:point_id>', views.point, name='point'),
    path('new', views.new_point, name='new_point'),
    path('new_point_post', views.new_point_post, name='new_point_post'),
    path('delete_point_post', views.delete_point_post, name='delete_point_post'),
    path('list', views.PointList.as_view())
]

users_app/urls.py
"""Defines URLs for USERS"""
from django.urls import path, include
from . import views

app_name = 'users_app'
urlpatterns = [
    # include default auth urls
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

dj_map_app/models.py
# from django.db import models
from django.contrib.gis.db import models
from django.db.models import Manager as GeoManager
from django.contrib.auth.models import User

# Create your models here.


class Point(models.Model):
    """A Geo Point"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    geom = models.PointField('longitude/latitude', blank=True, null=True)
    objects = GeoManager()
    srid = models.FloatField(blank=True, null=True, default=4326)


def __str__(self):
    """Retrun string rep of this model"""
    return self.text

users_app/models.py
from django.db import models

# Create your models here.

dj_map_app/forms.py
from django import forms
from .models import Point


class PointForm(forms.ModelForm):
    class Meta:
        model = Point
        fields = ['text']
        labels = {'text': ''}

dj_map_app/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from .models import Point
from .forms import PointForm
from django.core.serializers import serialize

from django.views import generic
from django.contrib.gis.geos import Point as geosPoint
from django.contrib.gis.db.models.functions import Distance

# TODO: get user location form browser instead of hard-coding
# cez
longitude = -108.585930
latitude = 37.348885

# tride
# longitude = -107.812286
# latitude = 37.937492

user_location = geosPoint(longitude, latitude, srid=4326)


def index(request):
    """Index page for maps app"""
    return render(request, 'dj_map_app/index.html')


@login_required
def large(request):
    """Page for maps"""
    return render(request, 'dj_map_app/large.html')


@login_required
def points(request):
    """Page for points"""
    # query the points model, filter by user
    points = Point.objects.filter(owner=request.user).order_by('date_added')

    # context is a dictionary of key/vals
    context = {'points': points}
    return render(request, 'dj_map_app/points.html', context)


@login_required
def points_data(request):
    """API for points"""
    points_as_geojson = serialize('geojson', Point.objects.all())
    return JsonResponse(json.loads(points_as_geojson))


@login_required
def nearby_points_data(request):
    """API for points"""
    distance = Distance('geom', user_location)
    points_as_geojson = Point.objects.annotate(distance=distance).order_by('distance')[0:15]
    points_as_geojson = serialize('geojson', points_as_geojson)
    return JsonResponse(json.loads(points_as_geojson))


@login_required
def point(request, point_id):
    """Page for single point"""
    # query the points model for matching point
    point = get_object_or_404(Point, id=point_id, owner=request.user)

    # context is a dictionary of key/vals
    context = {'point': point}
    return render(request, 'dj_map_app/point.html', context)


@login_required
def new_point(request):
    """Make new single point"""
    if request.method != 'POST':
        form = PointForm()
    else:
        form = PointForm(data=request.POST)
        if form.is_valid():
            # Don't save the form until the user has been set
            new_point = form.save(commit=False)
            new_point.owner = request.user
            new_point.save()
            return redirect('dj_map_app:points')

    # Display blank/invalid form
    context = {'form': form}
    return render(request, 'dj_map_app/new_point.html', context)


@login_required
def new_point_post(request):
    """Make new single point"""
    new_point = Point()
    new_point.text = request.POST.get('text', None)
    geom = request.POST.get('geometry')
    new_point.geom = request.POST.get('geometry')
    new_point.owner = request.user
    new_point.save()
    return HttpResponse(json.dumps(geom), content_type="application/json")


@login_required
def delete_point_post(request):
    """Delete single point"""
    feature = request.POST.get('feature', None)
    query = Point.objects.get(pk=feature)
    query.delete()

    # Find the point and delete it
    return HttpResponse(json.dumps(feature), content_type="application/json")


class PointList(generic.ListView):
    model = Point
    context_object_name = 'points'
    points = Point.objects.annotate(distance=Distance('geom', user_location))
    queryset = points.order_by('distance')[0:6]
    template_name = 'dj_map_app/list.html'

users_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
    else:
        # process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()

            # log user in and redirect to home Page
            login(request, new_user)
            return redirect('dj_map_app:index')

    # Display blank form or invalid
    context = {'form': form}
    return render(request, 'registration/register.html', context)

dj_map_app/templates/dj_map_app/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>DJ Maps</title>

  {% load bootstrap4 %}
  {# pip install django-bootstrap4 #}

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
  {% block extra_assets %}{% endblock extra_assets %}

</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'dj_map_app:index' %}">DJ Maps</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle Navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dj_map_app:points' %}">
            Points
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dj_map_app:large' %}">
            Large
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="navbar-text"> Hello, {{ user.username }}.</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users_app:logout' %}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users_app:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users_app:login' %}">Log in</a>
        </li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

<footer class="page-footer font-small blue pt-4">
  {% if dump %}
  <div  class="border">
    <h2>DUMPED VARS</h2>
    {{ dump }}
  </div>
  {% endif %}

  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://devincowan.host/">DC</a>
  </div>

</footer>

</html>

dj_map_app/templates/dj_map_app/index.html
{% extends "dj_map_app/base.html" %} #this child template extends base

{% block page_header %}
<div class="jumbotron">
  <h1 class="display-3">Store your maps.</h1>

  <p class="lead">Upload maps and sort through them.</p>

  <a class="btn btn-lg btn-primary" href="{% url 'users_app:register' %}" role="button">
    Register &raquo;
    {# html element ">>" #}
  </a>
</div>
{% endblock page_header %}

{% block content %}

<p>Map APP content is filled here</p>

{% endblock content %}

dj_map_app/templates/dj_map_app/large.html
{% extends "dj_map_app/base.html" %}

{% load static %}

{% block extra_assets %}
{% load leaflet_tags %}
  {% leaflet_js %}
  {% leaflet_css %}

  <script src="{% static 'leaflet-ajax/dist/leaflet.ajax.min.js' %}"></script>
  <script src="{% static 'leaflet-routing-machine/dist/leaflet-routing-machine.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'leaflet-routing-machine/dist/leaflet-routing-machine.css' %}"></script>
  <script src="{% static 'spin.js/spin.min.js' %}"></script>
  <script src="{% static 'leaflet-spin/leaflet.spin.js' %}"></script>

{% endblock %}

{% block page_header %}
<h1>Large map</h1>
{% endblock page_header %}

{% block content %}

<div id="dj_map"></div>
<style>
#dj_map {
  height: 100vh;
}
</style>
<script>
  var map = L.map("dj_map").setView([37.7035675, -107.9], 10);

  var url = 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
  attr ='Map data: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)',
  topo = new L.TileLayer(url, {maxZoom: 17, attribution: attr});

  url = 'https://tile.thunderforest.com/outdoors/{z}/{x}/{y}.png?apikey=3df4052ee1414ec4955e461b5f0d19c8'
  outdoor = new L.TileLayer(url, {maxZoom: 17});

  url = 'https://tile.thunderforest.com/transport/{z}/{x}/{y}.png?apikey=3df4052ee1414ec4955e461b5f0d19c8'
  transportation = new L.TileLayer(url, {maxZoom: 17});

  var geojsonPointLayer = new L.GeoJSON.AJAX("{% url 'dj_map_app:nearby_points_data' %}", {
    // style: function(feature) {
    //   return {
    //     color: "green"
    //   };
    // },
    // pointToLayer: function(feature, latlng) {
    //   return new L.CircleMarker(latlng, {
    //     radius: 5,
    //     fillOpacity: 0.85
    //   });
    // },

    // onEachFeature:function(feature, layer) {
    //   layer.bindPopup(feature.properties.text.toString());
    // }
  });

  var baseMaps = {
    "Topo": topo,
    "Outdoor": outdoor,
    "Transportation": transportation
  };

  var overlayMaps = {
    "Points": geojsonPointLayer
  };

  L.control.layers(baseMaps, overlayMaps).addTo(map);

  // Use topo by default
  map.addLayer(topo);

  control = L.Routing.control({
    // style for the routing line
    // lineOptions: {
    //    styles: [{color: 'white', opacity: 1, weight: 5}]
    // }
  })
  control.addTo(map);

  function createButton(label, container) {
    var btn = L.DomUtil.create('button', '', container);
    btn.setAttribute('type', 'button');
    btn.innerHTML = label;
    return btn;
  }

  geojsonPointLayer.on('click', function(e){
    // TODO: remove this duplication with map.onclick
    var container1 = L.DomUtil.create('div'),
    startBtn = createButton('From here', container1),
    destBtn = createButton('To here', container1),
    deleteBtn = createButton('Delete', container1);

    L.popup()
    .setContent(container1)
    .setLatLng(e.latlng)
    .openOn(map);
    L.DomEvent.on(startBtn, 'click', function() {
        control.spliceWaypoints(0, 1, e.latlng);
        map.closePopup();
    });

    L.DomEvent.on(destBtn, 'click', function() {
      control.spliceWaypoints(control.getWaypoints().length - 1, 1, e.latlng);
      map.closePopup();
        });

    L.DomEvent.on(deleteBtn, 'click', function() {
      console.log(e.layer.feature);
      $.ajax(
        {
          type:"POST",
          url: "{% url 'dj_map_app:delete_point_post' %}",
          data:{
            feature: e.layer.feature.properties.pk,
            csrfmiddlewaretoken: '{{ csrf_token }}'
          },
          success: function( data )
          {
            map.removeLayer(e.layer.feature);
            alert("Point deleted");

          },
          error: function (response) {
            console.log(response)
          }
        }
      );
      map.closePopup();
      // TODO: hide the point
        });
  });

  map.on('click', function(e) {
    var container = L.DomUtil.create('div'),
    startBtn = createButton('From here', container),
    destBtn = createButton('To here', container),
    saveBtn = createButton('Save', container);

    L.popup()
    .setContent(container)
    .setLatLng(e.latlng)
    .openOn(map);

    L.DomEvent.on(startBtn, 'click', function() {
        control.spliceWaypoints(0, 1, e.latlng);
        map.closePopup();
    });

    L.DomEvent.on(destBtn, 'click', function() {
      control.spliceWaypoints(control.getWaypoints().length - 1, 1, e.latlng);
      map.closePopup();
        });

    L.DomEvent.on(saveBtn, 'click', function() {
      // var myIcon = L.icon({
      //   iconUrl: 'my-icon.png',
      //   iconSize: [38, 95],
      //   iconAnchor: [22, 94],
      //   popupAnchor: [-3, -76],
      //   shadowUrl: 'my-icon-shadow.png',
      //   shadowSize: [68, 95],
      //   shadowAnchor: [22, 94]
      // });
      // mark = L.marker(e.latlng, {icon: myIcon});
      mark = L.marker(e.latlng);
      mark.addTo(map);
      //
      $.ajax(
        {
          type:"POST",
          url: "{% url 'dj_map_app:new_point_post' %}",
          data:{
            geometry: JSON.stringify(mark.toGeoJSON().geometry),
            // TODO: pop input for text
            text: 'AJAX TEST',
            csrfmiddlewaretoken: '{{ csrf_token }}'
          },
          success: function( data )
          {
            // $( '#like'+ id ).removeClass('btn btn-primary btn-lg');
            // $( '#like'+ id ).addClass('btn btn-success btn-lg');
          },
          error: function (response) {
            console.log(response)
          }
        }
      );
      map.closePopup();
    });
});

</script>

{% endblock content %}

dj_map_app/templates/dj_map_app/list.html
{% extends "dj_map_app/base.html" %} #this child template extends base

{% block page_header %}
<h1>Nearby Points</h1>
{% endblock page_header %}

{% block content %}

{% if points %}
<ul>
  {% for point in points %}
  <li>
    {{ point.text }}: {{point.distance}}
  </li>
  {% endfor %}
</ul>
{% endif %}

{% endblock content %}

dj_map_app/templates/dj_map_app/new_point.html
{% extends "dj_map_app/base.html" %} #this child template extends base

{% block content %}

<p>Add new point</p>

<form action="{% url 'dj_map_app:new_point' %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }} {# Render as paragraph #}
  <button name="submit">Add Point</button>
</form>


{% endblock content %}

dj_map_app/templates/dj_map_app/point.html
{% extends "dj_map_app/base.html" %} #this child template extends base

{% block content %}

<p>Single Point Content</p>

<p>ID: {{ point.id }}</p>
<p>Text: {{ point.text }}</p>
<p>Created: {{ point.date_added | date:'M d, Y H:i'}}</p>{# jinja filter #}
<p>Geom: {{ point.geom }}</p>


{% endblock content %}

dj_map_app/templates/dj_map_app/points.html
{# {% extends "dj_map_app/base.html" %} #this child template extends base #}
{# TODO: leaflet only loads if the template doesn't extend base... #}

{% load leaflet_tags %}

{% leaflet_css %}
{% leaflet_js %}

{% load static %}
<script src="{% static 'leaflet-ajax/dist/leaflet.ajax.min.js' %}"></script>
<script src="{% static 'spin.js/spin.min.js' %}"></script>
<script src="{% static 'leaflet-spin/leaflet.spin.js' %}"></script>

{% block page_header %}
<h1>Points</h1>
{% endblock page_header %}

{% block content %}

<script type="text/javascript">
  function map_init_basic (map, options) {
    var geojsonPointLayer = new L.GeoJSON.AJAX("{% url 'dj_map_app:points_data' %}", {
      onEachFeature:function(feature, layer) {
        layer.bindPopup(feature.properties.text.toString());
      }
    });
    geojsonPointLayer.addTo(map);
    console.log(geojsonPointLayer);
  }
</script>

{% leaflet_map "dj-map" callback="window.map_init_basic" %}

<ul>
  {% for point in points %}
  <li><h3>
    <a href="{% url 'dj_map_app:point' point.id %}">{{ point}}</a>
  </h3></li>
  {% empty %}
  <li><h3>No points added yet...</h3></li>
  {% endfor %}
</ul>

<h3><a href="{% url 'dj_map_app:new_point' %}">Add a new Point</a></h3>

{% endblock content %}

dj_map_app/templates/index.html
{% extends "base.html" %} #this child template extends base

{% block page_header %}
<div class="jumbotron">
  <h1 class="display-3">Store your maps.</h1>

  <p class="lead">Upload maps and sort through them.</p>

  <a class="btn btn-lg btn-primary" href="{% url 'users_app:register' %}" role="button">
    Register &raquo;
    {# html element ">>" #}
  </a>
</div>
{% endblock page_header %}

{% block content %}

<p>Map APP content is filled here</p>

{% endblock content %}

dj_map_app/templates/large.html
{% extends "base.html" %} #this child template extends base

{% block content %}

<p>LARGE MAP CONTENT</p>

{% endblock content %}

dj_map_app/templates/new_point.html
{% extends "base.html" %} #this child template extends base

{% block content %}

<p>Add new point</p>

<form action="{% url 'dj_map_app:new_point' %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }} {# Render as paragraph #}
  <button name="submit">Add Point</button>
</form>


{% endblock content %}

dj_map_app/templates/point.html
{% extends "base.html" %} #this child template extends base

{% block content %}

<p>Single Point Content</p>

<p>ID: {{ point.id }}</p>
<p>Text: {{ point.text }}</p>
<p>Created: {{ point.date_added | date:'M d, Y H:i'}}</p>{# jinja filter #}


{% endblock content %}

dj_map_app/templates/points.html
{# {% extends "base.html" %} #this child template extends base #}
{# TODO: leaflet only loads if the template doesn't extend base... #}

{% load leaflet_tags %}

{% leaflet_css %}
{% leaflet_js %}

{% load static %}
<script src="{% static 'leaflet-ajax/dist/leaflet.ajax.min.js' %}"></script>
<script src="{% static 'spin.js/spin.min.js' %}"></script>
<script src="{% static 'leaflet-spin/leaflet.spin.js' %}"></script>

{% block page_header %}
<h1>Points</h1>
{% endblock page_header %}

{% block content %}

<script type="text/javascript">
  function map_init_basic (map, options) {
    var geojsonPointLayer = new L.GeoJSON.AJAX("{% url 'dj_map_app:points_data' %}", {
      onEachFeature:function(feature, layer) {
        layer.bindPopup(feature.properties.text.toString());
      }
    });
    geojsonPointLayer.addTo(map);
    console.log(geojsonPointLayer);
  }
</script>

{% leaflet_map "dj-map" callback="window.map_init_basic" %}

<ul>
  {% for point in points %}
  <li><h3>
    <a href="{% url 'dj_map_app:point' point.id %}">{{ point}}</a>
  </h3></li>
  {% empty %}
  <li><h3>No points added yet...</h3></li>
  {% endfor %}
</ul>

<h3><a href="{% url 'dj_map_app:new_point' %}">Add a new Point</a></h3>

{% endblock content %}